
CREATE DATABASE MINSA;
use MINSA;


CREATE TABLE SECCIONES ( 
   ID_SECCION int NOT NULL AUTO_INCREMENT PRIMARY KEY,
   SECCION varchar(40) NOT NULL,
   FECHA_CREACION DATE
);


CREATE TABLE  ROLES  (
   ID_ROL int NOT NULL AUTO_INCREMENT PRIMARY KEY,
   ID_SECCION int NOT NULL,
   ROL varchar(25) NOT NULL, 
   FECHA_CREACION DATE,
   FOREIGN KEY (ID_SECCION) REFERENCES SECCIONES(ID_SECCION)
);

CREATE TABLE PERMISOS (
  ID_PERMISO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_ROL int NOT NULL,
  P_CONSULTAR VARCHAR(1),
  P_AGREGAR VARCHAR(1),
  P_MODIFICAR VARCHAR(1),
  P_ELIMINAR VARCHAR(1),
  P_TODO VARCHAR(1),
  FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL)
);

CREATE TABLE MEDICOS (
ID_MEDICO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE1 VARCHAR(20) NOT NULL,
NOMBRE2 VARCHAR(20),
APELLIDO1 VARCHAR(20) NOT NULL,
APELLIDO2 VARCHAR(20),
ESPECIALIDAD1 VARCHAR(40),
ESPECIALIDAD2 VARCHAR(40),
ESPECIALIDAD3 VARCHAR(40),
OTRAS TEXT,
IDONEIDAD VARCHAR(40) NOT NULL,
CEDULA VARCHAR(40) NOT NULL,
SEXO VARCHAR (1) NOT NULL,
TELEFONO VARCHAR (20),
CORREO VARCHAR(40)
);

CREATE TABLE ENFERMERAS (
ID_MEDICO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE1 VARCHAR(20) NOT NULL,
NOMBRE2 VARCHAR(20),
APELLIDO1 VARCHAR(20) NOT NULL,
APELLIDO2 VARCHAR(20),
ESPECIALIDAD VARCHAR(40),
OTRAS TEXT,
IDONEIDAD VARCHAR(40) NOT NULL,
CEDULA VARCHAR(40) NOT NULL,
SEXO VARCHAR (1) NOT NULL,
TELEFONO VARCHAR (20),
CORREO VARCHAR(40)
);

CREATE TABLE USUARIOS (
ID_USUARIO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_ROL int NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
APELLIDO VARCHAR(20) NOT NULL,
CORREO VARCHAR(40),
NICK VARCHAR(25) NOT NULL,
PASS VARCHAR(25) NOT NULL,
FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL)
);

CREATE TABLE AREAS ( 
   ID_AREA int NOT NULL AUTO_INCREMENT PRIMARY KEY,
   AREA varchar(40) NOT NULL,
   ESTADO INT DEFAULT 0
);

CREATE TABLE CUARTOS ( 
   ID_CUARTO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
   CUARTO int NOT NULL,
   ID_AREA int NOT NULL,
   ESTADO VARCHAR(1) DEFAULT 'a',
   FOREIGN KEY (ID_AREA) REFERENCES AREAS(ID_AREA)
);

CREATE TABLE CAMAS ( 
   ID_CAMA int NOT NULL AUTO_INCREMENT PRIMARY KEY,
   CAMA int NOT NULL,
   ID_CUARTO INT NOT NULL,
   USO VARCHAR(1) DEFAULT 'l',
   ESTADO VARCHAR(1) DEFAULT 'a',
   FOREIGN KEY (ID_CUARTO) REFERENCES CUARTOS(ID_CUARTO)
);


CREATE TABLE PROVINCIAS (
ID_PROVINCIA int NOT NULL AUTO_INCREMENT PRIMARY KEY,
PROVINCIA VARCHAR(40)
);

CREATE TABLE DISTRITOS (
ID_DISTRITO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PROVINCIA int NOT NULL,
DISTRITO VARCHAR(40),
FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIAS(ID_PROVINCIA)
);

CREATE TABLE CORREGIMIENTOS (
ID_CORREGIMIENTO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PROVINCIA int NOT NULL,
ID_DISTRITO int NOT NULL,
CORREGIMIENTO VARCHAR(40),
FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIAS(ID_PROVINCIA),
FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITOS(ID_DISTRITO)
);

CREATE TABLE PACIENTES (
ID_PACIENTE int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_AREA int NOT NULL,
ID_CUARTO int NOT NULL,
ID_CAMA int NOT NULL,
ID_PROVINCIA int NOT NULL,
ID_DISTRITO int NOT NULL,
ID_CORREGIMIENTO int NOT NULL,
NOMBRE1 VARCHAR(20) NOT NULL,
NOMBRE2 VARCHAR(20),
APELLIDO1 VARCHAR(20) NOT NULL,
APELLIDO2 VARCHAR(20),
DIAGNOSTICO TEXT,
PROCEDENCIA VARCHAR(40),
SEGURO VARCHAR(40),
RESPONSABLES TEXT,
EDAD int NOT NULL,
FECHA_NAC DATE NOT NULL,
CEDULA VARCHAR(40) NOT NULL,
SEXO VARCHAR (1) NOT NULL,
TIPAJE VARCHAR (10) NOT NULL,
TELEFONO VARCHAR (20),
RELIGION VARCHAR(40),
BARRIO VARCHAR (40),
CALLE VARCHAR (20),
NUMCASA int,
ESTADO INT DEFAULT 0,
FECHA DATE,
FOREIGN KEY (ID_AREA) REFERENCES AREAS(ID_AREA),
FOREIGN KEY (ID_CUARTO) REFERENCES CUARTOS(ID_CUARTO),
FOREIGN KEY (ID_CAMA) REFERENCES CAMAS(ID_CAMA),
FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIAS(ID_PROVINCIA),
FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITOS(ID_DISTRITO),
FOREIGN KEY (ID_CORREGIMIENTO) REFERENCES CORREGIMIENTOS(ID_CORREGIMIENTO)
);


CREATE TABLE CONSULTAS (
ID_CONSULTA int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PACIENTE int NOT NULL,
ID_MEDICO int NOT NULL,
MVISITA TEXT,
ALERGIA TEXT,
APP TEXT,
AHF TEXT,
AQX TEXT,
INDICACIONES TEXT,
EXAFISICO TEXT,
DIAGNOSTICO TEXT,
FECHA_HORA DATE,
OBSERVACION TEXT,
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO)
);
 

CREATE TABLE ENFERMERIAS (
ID_ENFERMERIA int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PACIENTE int NOT NULL,
ID_MEDICO int NOT NULL,
DIAGNOSTICO TEXT,
PROCEDENCIA VARCHAR(40),
SEGURO VARCHAR(40),
IDIOMA VARCHAR(40),
RESPONSABLES TEXT,
SVITAT FLOAT,
SVITAP FLOAT,
SVITAR FLOAT,
SVITAPA FLOAT,
SVITASO2 FLOAT,
FLLEGADA VARCHAR(20),
CONDICION VARCHAR(20),
GLASGOWVERVAL INT,
GLASGOWVOJOS INT,
GLASGOWMOTOR INT,
FECHA DATE,
TURNO VARCHAR (20),
OBSERVACION TEXT,
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO)
);


CREATE TABLE HMEDI (
ID_HMEDICAM  int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PACIENTE int NOT NULL,
USR_CREA int NOT NULL,
FECHA_CREA DATE,
USR_MODIFICA int NOT NULL,
FECHA_MODIFICA DATE,
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
);


CREATE TABLE DIETAS (
ID_DIETA  int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PACIENTE int NOT NULL,
DIETA VARCHAR (20),
NOTA TEXT,
USR_CREA int NOT NULL,
FECHA_CREA DATE,
USR_MODIFICA int NOT NULL,
FECHA_MODIFICA DATE,
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
);


CREATE TABLE CIRCULACION (
ID_CIRCULACION  int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PACIENTE int NOT NULL,
SELLOHEPARINA VARCHAR(2),
VENOCLISI VARCHAR (100),
EDEMAS VARCHAR(2),
ELOCALIZACION VARCHAR (100),
HERIDA VARCHAR(2),
HERIDA_TIPO VARCHAR (50),
HEMORRAGIA VARCHAR(2),
HEMO_LUGAR VARCHAR (100),
USR_CREA int NOT NULL,
FECHA_CREA DATE,
USR_MODIFICA int NOT NULL,
FECHA_MODIFICA DATE,
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
);

CREATE TABLE MUCOSA_ORAL (
ID_MUCOSA  int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PACIENTE int NOT NULL,
ESTADO VARCHAR(1),
CAUSAS TEXT,
DENTINCION VARCHAR(1),
LROSADA_COLOR VARCHAR(40),
LENGUA_HUMEDA VARCHAR(1),
REFLE_DEGLUCION VARCHAR(1),
REFLE_CAUSA TEXT,
USR_CREA int NOT NULL,
FECHA_CREA DATE,
USR_MODIFICA int NOT NULL,
FECHA_MODIFICA DATE,
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
);


CREATE TABLE COMUNICACION (
ID_DOLOR  int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PACIENTE int NOT NULL,
COMU_VERBAL VARCHAR(1) DEFAULT 'n',
DISFASIA VARCHAR(1) DEFAULT 'n', 
AFASIA VARCHAR(1) DEFAULT 'n', 
DISATRIA VARCHAR(1) DEFAULT 'n', 
DISFEMIA VARCHAR(1) DEFAULT 'n', 
OBS TEXT,
USR_CREA int NOT NULL,
FECHA_CREA DATE,
USR_MODIFICA int NOT NULL,
FECHA_MODIFICA DATE,
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
);

CREATE TABLE ELI_URINARIA (
ID_URINARIA  int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PACIENTE int NOT NULL,
ESPONTANEA VARCHAR(1) DEFAULT 'n',
PAMPER VARCHAR(1) DEFAULT 'n', 
SONDA_SUPRAPUBICA VARCHAR(1) DEFAULT 'n', 
SONDA_URETRAL VARCHAR(1) DEFAULT 'n', 
COLOR VARCHAR(25), 
OLOR VARCHAR(25), 
OBS TEXT,
USR_CREA int NOT NULL,
FECHA_CREA DATE,
USR_MODIFICA int NOT NULL,
FECHA_MODIFICA DATE,
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
);


CREATE TABLE ELI_INTESTINAL (
ID_INSTESTINAL  int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PACIENTE int NOT NULL,
FRECUENCIA INT ,
NORMAL VARCHAR(1) DEFAULT 'n', 
ESTRENIMIENTO VARCHAR(1) DEFAULT 'n', 
DIARREA VARCHAR(1) DEFAULT 'n', 
COLOR VARCHAR(25), 
OBS TEXT,
USR_CREA int NOT NULL,
FECHA_CREA DATE,
USR_MODIFICA int NOT NULL,
FECHA_MODIFICA DATE,
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
);


CREATE TABLE DEAMBULACION (
ID_DEAMBULACION  int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PACIENTE int NOT NULL,
ALTERADA VARCHAR(1) DEFAULT 'n',
CAUSA TEXT,
DEFORMACION VARCHAR(1) DEFAULT 'n',
DEFO_LUGAR VARCHAR (100),
TONO_NORMAL VARCHAR(1) DEFAULT 'n',
TONO_DISMINUIDA VARCHAR(1) DEFAULT 'n',
OBS TEXT,
USR_CREA int NOT NULL,
FECHA_CREA DATE,
USR_MODIFICA int NOT NULL,
FECHA_MODIFICA DATE,
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
);



CREATE TABLE DOLOR (
ID_DOLOR  int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PACIENTE int NOT NULL,
EVA INT,
LOCALIZACION TEXT,
USR_CREA int NOT NULL,
FECHA_CREA DATE,
USR_MODIFICA int NOT NULL,
FECHA_MODIFICA DATE,
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
);

CREATE TABLE ESTADOS_PIEL (
ID_ESTADO_PIEL  int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PACIENTE int NOT NULL,
COLOR_ALTERADO VARCHAR(1) DEFAULT 'n',
OBS_COLOR TEXT,
INTEGRA VARCHAR(1) DEFAULT 'n',
HIDRATADA VARCHAR(1) DEFAULT 'n',
SUB_HIDRATADA VARCHAR(1) DEFAULT 'n',
MACERADA VARCHAR(1) DEFAULT 'n',
OBS TEXT,
USR_CREA int NOT NULL,
FECHA_CREA DATE,
USR_MODIFICA int NOT NULL,
FECHA_MODIFICA DATE,
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
);